---
title: "Homework 7"
author: "Anna Moeller"
date: "April 1, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## Problem 9.
Asymptotic efficiency of method-of-moments estimator
```{r}
x <- 0:20
y <- (1 + 2*x)/((1 + x)^2)
plot(x, y, type = "l" )
```

## Problem 10
```{r}
n <- c(10, 25)
theta <- c(.5, 2, 5)
nsim <- 100000

# Summary functions
mae <- function(x, theta) mean(abs(x - theta))
rmse <- function(x, theta) sqrt(mean((x - theta)^2))

sd_mle <- sd_mom <- rmse_mle <- rmse_mom <- mae_mle <- mae_mom <- 
  matrix(NA, 
         nrow = length(n), 
         ncol = length(theta), 
         dimnames = list(n, theta) )
# For one n and one theta)
for(j in 1:length(n)){
  for(k in 1:length(theta)){
    # Simulation
    mle <- mom <- rep(NA, nsim)
    for(i in 1:nsim){
      X <- rbeta(n[j], 1/theta[k], 1)
      mle[i] <- -sum(log(X))/n[j]
      mom[i] <- (1-mean(X))/mean(X)
    }
    # Summaries
    # SD
    sd_mle[j, k] <- sd(mle)
    sd_mom[j, k] <- sd(mom)
  
    # RMSE
    rmse_mle[j, k] <- rmse(mle, theta[k])
    rmse_mom[j, k] <- rmse(mom, theta[k])
  
    # MAE
    mae_mle[j, k] <- mae(mle, theta[k])
    mae_mom[j, k] <- mae(mom, theta[k])
  }
}

 res <- list(sd_mle, sd_mom, rmse_mle, rmse_mom, mae_mle, mae_mom) %>%
   map(., as_tibble) %>% 
   do.call(bind_rows, .) %>% 
   mutate(Estimator = rep(c("MLE", "MLE", "MOM", "MOM"), 3),
          n = rep(n, 6),
          Statistic = rep(c("SD", "RMSE", "MAE"), each = 4) ) %>% 
   gather(theta, Estimate, 1:3) %>% 
   arrange(n, theta, Estimator) %>% 
   select(n, theta, Estimator, Statistic, Estimate) 
 
 res %>% print(n = Inf)
 
 # Make a graph
 ggplot(res, aes(theta, Estimate, group = Estimator)) + 
   geom_path(aes(color = factor(Estimator, levels = rev(levels(factor(res$Estimator))))))+ 
   facet_grid(n ~ Statistic, labeller = labeller(.rows = label_both) ) + 
   theme(legend.title = element_blank() ) 
```

The MLE estimate always has a lower value across MAE, RMSE, and SD, for both small sample sizes. 

```{r, include = F}
#' I'm keeping this because it's what Josh helped me with. I'm not totally sure it's working for large nsim. 

# sim_fun <- function(x){
#   tibble::tibble(
#     X = rbeta(x$n, 1/x$theta, 1) # df with n rows, col X
#   ) %>% 
#   summarise(
#     MLE = -sum(log(X))/x$n,
#     MOM = (1-mean(X))/mean(X)
#   ) %>% 
#   mutate_at(vars(MLE, MOM), round, digits = 3)
# } # Returns df with 1 row, cols MLE and MOM
# 
# wrapper <- function(n, theta){
#   tst <- tibble::tibble(
#       n = n # df with length(n) rows, 1 col
#     ) %>% 
#     tidyr::expand(n, theta = theta) %>% 
#     group_by(n, theta) %>% 
#     do(sim_fun(.)) %>% # Do sim_fun for each n and theta
#     tidyr::gather(Method, Statistic, -n, -theta)
#   return(tst)
# }
# 
# out <- purrr::rerun(
#   nsim, 
#   wrapper(n = n, theta = theta) ) %>% 
#   bind_rows() %>% 
#   group_by(n, theta, Method) %>% 
#   summarise(
#     SD = sd(Statistic),
#     RMSE = rmse(Statistic),
#     MAE = mae(Statistic)
#   )
  

    
```
